# Generated by Django 3.1.12 on 2023-03-24 23:24

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, verbose_name='_id')),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=36)),
                ('iso3', models.CharField(max_length=3)),
                ('iso2', models.CharField(max_length=2)),
                ('numeric_code', models.CharField(max_length=3)),
                ('phone_code', models.CharField(max_length=16)),
                ('capital', models.CharField(max_length=20, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=39)),
                ('currency_symbol', models.CharField(max_length=6)),
                ('tld', models.CharField(max_length=3)),
                ('native', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=8, null=True)),
                ('subregion', models.CharField(max_length=25, null=True)),
                ('timezones', djongo.models.fields.JSONField(default=list)),
                ('translations', djongo.models.fields.JSONField()),
                ('latitude', models.CharField(max_length=12)),
                ('longitude', models.CharField(max_length=13)),
                ('emoji', models.CharField(max_length=2)),
                ('emojiU', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
